### ISSUE TITLE
Mostrar el nombre de usuario al logearse

### ISSUE THREAD

**Issue by IvanCh123** [IvanCh123/TCU-WebPage#2]
Esto sería que en el momento que se logea exitosamente, mostrar el nombre de usuario en el navbar y en este un dropdown con un link al logout (falta implementar).

**Comment by IvanCh123** [comment]
Esto ya se está haciendo de cierta manera, pero es necesario recargar la página para que se vea, este es el problema principal

**Comment by SteffFernandez** [comment]
Issue resuelto bbd452e7a29e0fe9e499d8759b247de7919ba7c2
